### PR TITLE
chore: customize blob storage url

### PR DESCRIPTION
**Pull request by wn-na**
A proposal for this issue https://github.com/microsoft/code-push-server/issues/54

### CODE REVIEW

**Comment by wn-na** [comment]
@microsoft-github-policy-service agree

**Comment by lucen-ms** [comment]
I'm sorry but we are not able to accept this change as it would require lot of time from us to test it. I suggest applying it to your fork. Thanks for understanding.

**Comment by shayangholami** [comment]
please check it, i was trying to find a solution for this and this person did it so easy its just 8 lines
now 4G changes

**Comment by shayangholami** [comment]
@wn-na thank u

**Pull request closed without merging**
